### ISSUE TITLE
Request for the dataset

### ISSUE THREAD

**Issue by irfanfadhullah** [HamedHojatian/HBF-Net#1]
Hello, can you provide a new link for the dataset? I cannot access the existing link

**Comment by irfanfadhullah** [comment]
Or is it possible if you to provide the step to generate that dataset? It will be more helpful for me. Thank you

**Comment by HamedHojatian** [comment]
Hello,
Since it is unsupervised learning, generating the dataset is very simple. 1) generate the CSI from the deepMIMO dataset based on your customize scenario, 2) compute the RSSI based on the CSI and eq (2) and normalized it, 3) merge the RSSI and CSI in a CSV file or .npy format 4) Use the RSSI as the input of the DNN and CSI to compute the loss function.
I will definitely upload the dataset soon.

**Comment by HamedHojatian** [comment]
Hello, 
The database has been uploaded with a new updated script in the main and utils files.

**Comment by irfanfadhullah** [comment]
Thank you for the information. I would like to ask you some questions about another dataset, maybe I will open an issue
